import { Event } from "./types";

export const sampleEvents: Event[] = [
  {
    id: "1",
    datetime: "mercredi 21 mai 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "2",
    datetime: "mercredi 21 mai 2025 à 16h30",
    name: "Le coffre à histoires",
    location: {
      place: "Médiathèque Geneviève Couteau",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "à partir de 3 ans",
  },
  {
    id: "3",
    datetime: "mercredi 21 mai 2025 à 16h30",
    name: "Échange ta lecture",
    location: {
      place: "Bibliothèque des changes",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "",
    audience: "8-12 ans",
  },
  {
    id: "4",
    datetime: "vendredi 23 mai 2025 à 19h00",
    name: "Rencontre avec Fabien Lebrun",
    location: {
      place: "Librairie les villes invisibles",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "en très libre",
  },
  {
    id: "5",
    datetime: "vendredi 23 mai 2025 à 19h00",
    name: "La Fête des voisins : pique nique zéro déchets & concours de pétanque (en partenariat avec Granit)",
    location: {
      place: "Porte de Palzaire",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "6",
    datetime: "vendredi 23 mai 2025 à 19h30",
    name: "Les Petites Scènes",
    location: {
      place: "Parc du Vallon",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "7",
    datetime: "vendredi 23 mai 2025 à 20h30",
    name: "Danse et musique : « [F] »",
    location: {
      place: "Auditorium du complexe de la Margerie",
      city: "GORGES",
      department: "44",
    },
    price: "5-8€",
    audience: "tout public à partir de 10 ans",
  },
  {
    id: "8",
    datetime: "vendredi 23 mai 2025 à 18h00",
    name: "SMÖLL FESTIVÖLL #11 : Slüg /RCD Soundsystem",
    location: {
      place: "Espace des Garennes",
      city: "SAINT LUMINE DE CLISSON",
      department: "44",
    },
    price: "prix libre",
    audience: "",
    url: "https://thesmollfestivoll.wixsite.com/thesmollfestivoll"
  },
  {
    id: "9",
    datetime: "samedi 24 mai 2025 à 10h00",
    name: "Balade nature",
    location: {
      place: "Médiathèque",
      city: "CUGAND",
      department: "85",
    },
    price: "",
    audience: "tout public de 4 à 12 ans avec accompagnateur, 1h30, sur inscription",
  },
  {
    id: "13",
    datetime: "samedi 24 mai 2025 à 10h00",
    name: "Grandeur nature : activités en familles",
    location: {
      place: "L'Abel Guinguette",
      city: "MONNIERES",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "14",
    datetime: "samedi 24 mai 2025 de 10h00",
    endTime: "17h00",
    name: "Atelier soudure Good Steel",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "15",
    datetime: "samedi 24 mai 2025 de 10h00",
    endTime: "17h00",
    name: "Festi'liens : rencontre avec les associations qui font bouger le Pallet",
    location: {
      place: "Salle polyvalente",
      city: "LE PALLET",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "16",
    datetime: "samedi 24 mai 2025",
    name: "Concert baroque : (Vivaldi, Pergolese, Bach)",
    location: {
      place: "Église Saint-Martin-de-Vertou",
      city: "VERTOU",
      department: "44",
    },
    price: "gratuit",
    audience: "",
  },
  {
    id: "17",
    datetime: "samedi 24 mai 2025",
    name: "LES MASCARADES",
    location: {
      place: "",
      city: "CLISSON",
      department: "44",
    },
    price: "gratuit",
    audience: "",
  },
  {
    id: "18",
    datetime: "samedi 24 mai 2025",
    name: "Festival Lid ar morrigan VII : Skálmöld (ISL, Viking Folk Metal) / Nytt Land (RU Folk Chamanique) / Grimner (SUE, Folk / Pagan Metal) / Tanneurs de Drac (FR Folk / Rock médiéval) / Boisson Divine (FR Heavy Folk Metal) / Cuélebre (ES Pagan folk traditionnel) / Sorcières (FR Black / folk metal) / Aelad (FR Folk acoustique) / Flétan (FR Rock Pagan)",
    location: {
      place: "Le Champilambart",
      city: "VALLET",
      department: "44",
    },
    price: "30€",
    audience: "",
  },
  {
    id: "19",
    datetime: "samedi 24 mai 2025",
    name: "SMÖLL FESTIVÖLL #11 : Avalanche Kaito /Cyril Cyril",
    location: {
      place: "tba",
      city: "SAINT LUMINE DE CLISSON",
      department: "",
    },
    price: "14€",
    audience: "",
    url: "https://thesmollfestivoll.wixsite.com/thesmollfestivoll"
  },
  {
    id: "20",
    datetime: "dimanche 25 mai 2025 de 8h00",
    endTime: "18h00",
    name: "Bonne Fontaine fait son vide-grenier",
    location: {
      place: "Bonne Fonaine",
      city: "VALLET",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "21",
    datetime: "dimanche 25 mai 2025 de 8h00",
    endTime: "18h00",
    name: "Vide Grenier",
    location: {
      place: "Espace Sévria",
      city: "HAYE FOUASSIERE",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "22",
    datetime: "dimanche 25 mai 2025 de 9h00",
    endTime: "17h00",
    name: "Vide Grenier",
    location: {
      place: "Super U",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "23",
    datetime: "dimanche 25 mai 2025 de 9h00",
    endTime: "18h00",
    name: "33ème salon des collectionneurs",
    location: {
      place: "Pavillon des Nourrices, Place de l'Hôtel de Ville, Moulin de la Tour",
      city: "MONTAIGU",
      department: "85",
    },
    price: "",
    audience: "",
  },
  {
    id: "24",
    datetime: "dimanche 25 mai 2025 de 14h00",
    endTime: "17h00",
    name: "Atelier couture Fil Good thématique",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "25",
    datetime: "dimanche 25 mai 2025 de 16h00",
    endTime: "21h00",
    name: "Les dominique : Rudy Box theater / Lambe Lambe / Chile tiempo y teatros en miniatura",
    location: {
      place: "I comme ICI",
      city: "SAINT LUMINE DE CLISSON",
      department: "44",
    },
    price: "PAF + adhésion prix libre",
    audience: "",
  },
  {
    id: "26",
    datetime: "dimanche 25 mai 2025",
    name: "LES MASCARADES",
    location: {
      place: "",
      city: "CLISSON",
      department: "44",
    },
    price: "gratuit",
    audience: "",
  },
  {
    id: "27",
    datetime: "mardi 27 mai 2025 à 18h30",
    name: "Conférence : « Moondog à travers le 20ème sicècle » par Amaury Cornut",
    location: {
      place: "Médiathèque",
      city: "CUGAND",
      department: "85",
    },
    price: "",
    audience: "tout public, 1h30, sur inscription de préférence",
  },
  {
    id: "28",
    datetime: "mardi 27 mai 2025 à 20h00",
    name: "Désembobinage présente « La cravate » d'Etienne Chaillou & Mathias Théry (projection/discussion)",
    location: {
      place: "Cercle Olivier de Clisson",
      city: "CLISSON",
      department: "44",
    },
    price: "prix libre",
    audience: "",
  },
  {
    id: "29",
    datetime: "mercredi 28 mai 2025 de 10h30",
    endTime: "12h00",
    name: "Club Connaître et Protéger la Nature (3-6 ans)",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "30",
    datetime: "mercredi 28 mai 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "31",
    datetime: "mercredi 28 mai 2025 à 15h00",
    name: "Le petit atelier : Book art",
    location: {
      place: "La Récupérette",
      city: "SAINT LUMINE DE CLISSON",
      department: "44",
    },
    price: "adhésion",
    audience: "",
  },
  {
    id: "32",
    datetime: "vendredi 30 mai 2025 à 18h00",
    name: "Nouvelle expo et vernissage de Gaëlle Jumelais",
    location: {
      place: "Librairie les villes invisibles",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "en très libre",
  },
  {
    id: "33",
    datetime: "vendredi 30 mai 2025 de 18h00",
    endTime: "03h00",
    name: "Vineyard Station Festival (dub-électro-reggae)",
    location: {
      place: "",
      city: "LA REMAUDIERE",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "34",
    datetime: "samedi 31 mai 2025",
    name: "Fête du jeu",
    location: {
      place: "Médiathèque Geneviève Couteau",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "35",
    datetime: "samedi 31 mai 2025",
    name: "Vineyard Station Festival (dub-électro-reggae)",
    location: {
      place: "",
      city: "LA REMAUDIERE",
      department: "44",
    },
    price: "",
    audience: "",
  },
  // Événements de juin 2025
  {
    id: "37",
    datetime: "dimanche 1er juin 2025",
    name: "Vide grenier",
    location: {
      place: "Rue des Ouches, Rue du Paradis, Bas Briacé",
      city: "LE LANDREAU",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "38",
    datetime: "dimanche 1er juin 2025 à 11h00",
    name: "DAMAline DUNE (lecture et poésie) : « les délices du patriarcat »",
    location: {
      place: "Au jardin du Paradis",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "10€",
    audience: "",
  },
  {
    id: "39",
    datetime: "dimanche 1er juin 2025 de 16h00",
    endTime: "21h00",
    name: "Les dominique : Grzzz (punk indus qui grince)",
    location: {
      place: "I comme ICI",
      city: "SAINT LUMINE DE CLISSON",
      department: "44",
    },
    price: "PAF + adhésion prix libre",
    audience: "",
  },
  {
    id: "40",
    datetime: "lundi 2 juin 2025 de 09h00",
    endTime: "17h00",
    name: "Lundi désossage (et grignotages !)",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "41",
    datetime: "mercredi 4 juin 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "42",
    datetime: "mercredi 4 juin 2025 à 16h30",
    name: "Rendez-vous conte",
    location: {
      place: "Bibliothèque des Changes",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "",
    audience: "à partir de 3 ans",
  },
  {
    id: "43",
    datetime: "mercredi 4 juin 2025 à 17h15",
    name: "Raconte-moi une histoire",
    location: {
      place: "Médiathèque Au fil des mots",
      city: "GORGES",
      department: "44",
    },
    price: "",
    audience: "à partir de 3 ans",
  },
  {
    id: "44",
    datetime: "jeudi 5 juin 2025 de 17h00",
    endTime: "20h00",
    name: "Atelier mécanique vélo pour femmes",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "45",
    datetime: "jeudi 5 juin 2025 de 18h00",
    endTime: "20h00",
    name: "Répétition ouverte au public de la chorale Vocal Vibes",
    location: {
      place: "Village Henri IV",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "46",
    datetime: "jeudi 5 juin 2025 à 20h00",
    name: "Conférence : Confier et accueillir un bébé allaité",
    location: {
      place: "Complexe de la Margerie",
      city: "GORGES",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "47",
    datetime: "vendredi 6 juin 2025",
    name: "Les Pestaculaires",
    location: {
      place: "",
      city: "MONTAIGU",
      department: "85",
    },
    price: "prix libre",
    audience: "",
  },
  {
    id: "48",
    datetime: "vendredi 6 juin 2025 dès 19h00",
    name: "Fête de la musique : DJ Bassline ft. Chilly Jay",
    location: {
      place: "Brut",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "entrée libre",
    audience: "",
  },
  {
    id: "49",
    datetime: "samedi 7 juin 2025",
    name: "Les Pestaculaires",
    location: {
      place: "",
      city: "MONTAIGU",
      department: "85",
    },
    price: "prix libre",
    audience: "",
  },
  {
    id: "50",
    datetime: "samedi 7 juin 2025 à partir de 15h00",
    name: "TOPO(S)#3- Label Parole : bibliothèque vivante / Un p'tit vélo dans la tête / mini-spectacle / Titre définitif* (*titre provisoire) / enquête sur lie / Parler de femmes « inconnues » / Le P.A.R.D.I / Le Bal à Boby / Haies vives",
    location: {
      place: "Divers lieux",
      city: "LA HAYE FOUASSIERE",
      department: "44",
    },
    price: "gratuit",
    audience: "",
  },
  {
    id: "51",
    datetime: "samedi 7 juin 2025 de 14h00",
    endTime: "17h00",
    name: "Atelier couture libre Fil Good",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "52",
    datetime: "samedi 7 juin 2025 de 10h00",
    endTime: "18h30",
    name: "MON PETIT FESTIVAL : 5ème édition",
    location: {
      place: "Espace Bellevue",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "gratuit-5€",
    audience: "",
  },
  {
    id: "53",
    datetime: "samedi 7 juin 2025 à 15h00",
    name: "Club ado",
    location: {
      place: "Médiathèque Geneviève Couteau",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "+13 ans",
  },
  {
    id: "54",
    datetime: "samedi 7 juin 2025 à partir de 17h00",
    name: "TBA",
    location: {
      place: "La Guinguette Cara'bella",
      city: "LE LANDREAU",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "55",
    datetime: "dimanche 8 juin 2025 de 8h00",
    endTime: "18h00",
    name: "Vide Grenier de l'Amicale Laïque de Mouzillon",
    location: {
      place: "Eugène Guérin, Route de la Prée, La Martinière",
      city: "MOUZILLON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "56",
    datetime: "dimanche 8 juin 2025 de 8h00",
    endTime: "18h00",
    name: "Vide Grenier",
    location: {
      place: "La Cantine d'Embreil",
      city: "SAINT JULIEN DE CONCELLES",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "57",
    datetime: "dimanche 8 juin 2025 de 16h00",
    endTime: "21h00",
    name: "Les dominique :Thomas Carabistouille / voyage de contes (tout public)",
    location: {
      place: "I comme ICI",
      city: "SAINT LUMINE DE CLISSON",
      department: "44",
    },
    price: "PAF + adhésion prix libre",
    audience: "",
  },
  {
    id: "58",
    datetime: "dimanche 8 juin 2025 à partir de 17h00",
    name: "TBA",
    location: {
      place: "La Guinguette Cara'bella",
      city: "LE LANDREAU",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "59",
    datetime: "mercredi 11 juin 2025 à 10h30",
    name: "Histoire pour petites oreilles",
    location: {
      place: "Médiathèque Au fil des mots",
      city: "GORGES",
      department: "44",
    },
    price: "",
    audience: "de 0 à 3 ans, sur inscription",
  },
  {
    id: "60",
    datetime: "mercredi 11 juin 2025 à 12h00",
    name: "Les interludes : Sieste musicale",
    location: {
      place: "Médiathèque Geneviève Couteau",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "61",
    datetime: "mercredi 11 juin 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "62",
    datetime: "jeudi 12 juin 2025 à 19h00",
    name: "Féminisme : « Être un allié », une soirée animée par Les Super Féministes : pour les hommes qui s'intéressent au féminisme mais qui ne savent pas par où commencer",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "prix libre",
    audience: "",
  },
  {
    id: "63",
    datetime: "vendredi 13 juin 2025 de 17h00",
    endTime: "23h00",
    name: "Portes ouvertes + AG + soirée festive",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "64",
    datetime: "vendredi 13 juin 2025 à 20h00",
    name: "Musique : Camille et Matthieu Saglio Cie Anaya",
    location: {
      place: "Médiathèque",
      city: "CLISSON",
      department: "44",
    },
    price: "gratuit",
    audience: "",
  },
  {
    id: "65",
    datetime: "vendredi 13 juin 2025 à 20h00",
    name: "Concert : Marteau / Pelegrin / Les hommes crabes",
    location: {
      place: "Les Papas Brasseurs",
      city: "CLISSON",
      department: "44",
    },
    price: "entrée libre",
    audience: "",
  },
  {
    id: "66",
    datetime: "samedi 14 juin 2025",
    name: "L'art dans les jardins",
    location: {
      place: "Fromaget & Gaumier",
      city: "CUGAND",
      department: "85",
    },
    price: "",
    audience: "",
  },
  {
    id: "67",
    datetime: "samedi 14 juin 2025 à 10h00",
    name: "Le tipi des petits",
    location: {
      place: "Médiathèque Geneviève Couteau",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "de 0 à 3 ans",
  },
  {
    id: "68",
    datetime: "samedi 14 juin 2025 à 10h30",
    name: "Café littéraire avec Anthony Gaté",
    location: {
      place: "Médiathèque",
      city: "CUGAND",
      department: "85",
    },
    price: "",
    audience: "tout public, 1h30, sur inscription de préférence",
  },
  {
    id: "69",
    datetime: "samedi 14 juin 2025 de 16h00",
    endTime: "00h00",
    name: "Fête de la musique",
    location: {
      place: "Centre Ville",
      city: "CLISSON",
      department: "44",
    },
    price: "gratuit",
    audience: "",
  },
  {
    id: "70",
    datetime: "samedi 14 juin 2025 à 23h00",
    name: "Concert : Koman Douman (reggae)",
    location: {
      place: "Café des cordeliers",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "71",
    datetime: "dimanche 15 juin 2025",
    name: "L'art dans les jardins",
    location: {
      place: "Fromaget & Gaumier",
      city: "CUGAND",
      department: "85",
    },
    price: "",
    audience: "",
  },
  {
    id: "72",
    datetime: "dimanche 15 juin 2025 de 16h00",
    endTime: "21h00",
    name: "Les dominique : Alexandre Chanoine / Neige percée / Le Crabe / Performance flamenco/noise/rap/xp",
    location: {
      place: "I comme ICI",
      city: "SAINT LUMINE DE CLISSON",
      department: "44",
    },
    price: "PAF + adhésion prix libre",
    audience: "",
  },
  {
    id: "73",
    datetime: "dimanche 15 juin 2025 à 16h30",
    name: "Concert de musique actuelle",
    location: {
      place: "Salle Sévria",
      city: "LA HAYE-FOUASSIERE",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "74",
    datetime: "mardi 17 juin 2025 à 20h00",
    name: "Brin de Sol'Haye / OH-N149",
    location: {
      place: "Château de Rochefort",
      city: "LA HAYE-FOUASSIERE",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "75",
    datetime: "mercredi 18 juin 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "76",
    datetime: "mercredi 18 juin 2025 à 16h30",
    name: "Le coffre à histoires",
    location: {
      place: "Médiathèque Geneviève Couteau",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "à partir de 3 ans",
  },
  {
    id: "77",
    datetime: "mercredi 18 juin 2025 à 20h00",
    name: "Concert : Soul Trap (blues/reggea)",
    location: {
      place: "Le Quebreizh",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "78",
    datetime: "vendredi 20 juin 2025 à 18h00",
    name: "Fête de la musique",
    location: {
      place: "Le Port",
      city: "LA HAYE-FOUASSIERE",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "79",
    datetime: "vendredi 20 juin 2025",
    name: "BRELFEST :...",
    location: {
      place: "verger du Petit Coubrenier",
      city: "CUGAND",
      department: "85",
    },
    price: "prix libre",
    audience: "",
  },
  {
    id: "80",
    datetime: "samedi 21 juin 2025 de 18h00",
    endTime: "22h00",
    name: "Soirée impro danse & musique avec Meritxell Checa Esteban et le groupe de musique La Berlue",
    location: {
      place: "Henri IV",
      city: "CLISSON",
      department: "44",
    },
    price: "5€ (pas de CB)",
    audience: "",
  },
  {
    id: "81",
    datetime: "samedi 21 juin 2025",
    name: "BRELFEST :...",
    location: {
      place: "verger du Petit Coubrenier",
      city: "CUGAND",
      department: "85",
    },
    price: "prix libre",
    audience: "",
  },
  {
    id: "82",
    datetime: "dimanche 22 juin 2025",
    name: "BRELFEST :...",
    location: {
      place: "verger du Petit Coubrenier",
      city: "CUGAND",
      department: "85",
    },
    price: "prix libre",
    audience: "",
  },
  {
    id: "83",
    datetime: "dimanche 22 juin 2025 de 14h00",
    endTime: "17h00",
    name: "Atelier couture Fil Good thématique",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "84",
    datetime: "mercredi 25 juin 2025 de 10h30",
    endTime: "12h00",
    name: "Club Connaître et Protéger la Nature (3-6 ans)",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "85",
    datetime: "mercredi 25 juin 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "86",
    datetime: "mercredi 25 juin 2025 à 16h30",
    name: "Club lecture jeunesse",
    location: {
      place: "Médiathèque Geneviève Couteau",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "9-12 ans",
  },
  {
    id: "87",
    datetime: "vendredi 27 juin 2025 à 19h00",
    name: "Blabla Night",
    location: {
      place: "Médiathèque Geneviève Couteau",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "88",
    datetime: "vendredi 27 juin 2025 à 19h00",
    name: "Apéro concert dans le parc : lecture musicale / Miam's : la chanson au menu",
    location: {
      place: "Médiathèque",
      city: "CUGAND",
      department: "85",
    },
    price: "tout public",
    audience: "",
  },
  {
    id: "89",
    datetime: "vendredi 27 juin 2025 à 19h30",
    name: "Soirée moules frites",
    location: {
      place: "Brut",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "",
    audience: "sur réservation",
  },
  {
    id: "90",
    datetime: "samedi 28 juin 2025",
    name: "Slam as you are souffle sa 2ème bougie : festival de Slam poésie",
    location: {
      place: "lieu TBA",
      city: "",
      department: "",
    },
    price: "",
    audience: "",
  },
  {
    id: "91",
    datetime: "samedi 28 juin 2025 à partir de 19h30",
    name: "Soirée Jeux de société avec Quentin de Chez L'Hippogriffe",
    location: {
      place: "Brut",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "",
    audience: "sur réservation",
  },
  // Événements passés
  {
    id: "10",
    datetime: "lundi 19 mai 2025 à 15h00",
    name: "Exposition photo",
    location: {
      place: "Médiathèque",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "11",
    datetime: "mardi 20 mai 2025 à 14h00",
    name: "Atelier d'écriture",
    location: {
      place: "Centre culturel",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "12",
    datetime: "mardi 20 mai 2025 de 21h00",
    endTime: "23h00",
    name: "Dev. ephemeride 2.0",
    location: {
      place: "Chez Amaury",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "36",
    datetime: "jeudi 22 mai 2025 à 20h00",
    name: "Club Ciné : « Grease »",
    location: {
      place: "Cinéma Le connétable (salle 1)",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  }
];
