import { Event } from "./types";

export const sampleEvents: Event[] = [
  {
    id: "1",
    datetime: "mercredi 21 mai 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "2",
    datetime: "mercredi 21 mai 2025 à 16h30",
    name: "Le coffre à histoires",
    location: {
      place: "Médiathèque Geneviève Couteau",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "à partir de 3 ans",
  },
  {
    id: "3",
    datetime: "mercredi 21 mai 2025 à 16h30",
    name: "Échange ta lecture",
    location: {
      place: "Bibliothèque des changes",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "",
    audience: "8-12 ans",
  },
  {
    id: "4",
    datetime: "vendredi 23 mai 2025 à 19h00",
    name: "Rencontre avec Fabien Lebrun",
    location: {
      place: "Librairie les villes invisibles",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "en très libre",
  },
  {
    id: "5",
    datetime: "vendredi 23 mai 2025 à 19h00",
    name: "La Fête des voisins : pique nique zéro déchets & concours de pétanque (en partenariat avec Granit)",
    location: {
      place: "Porte de Palzaire",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "6",
    datetime: "vendredi 23 mai 2025 à 19h30",
    name: "Les Petites Scènes",
    location: {
      place: "Parc du Vallon",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "7",
    datetime: "vendredi 23 mai 2025 à 20h30",
    name: "Danse et musique : « [F] »",
    location: {
      place: "Auditorium du complexe de la Margerie",
      city: "GORGES",
      department: "44",
    },
    price: "5-8€",
    audience: "tout public à partir de 10 ans",
  },
  {
    id: "8",
    datetime: "vendredi 23 mai 2025 à 18h00",
    name: "SMÖLL FESTIVÖLL #11 : Slüg /RCD Soundsystem",
    location: {
      place: "Espace des Garennes",
      city: "SAINT LUMINE DE CLISSON",
      department: "44",
    },
    price: "prix libre",
    audience: "",
    url: "https://thesmollfestivoll.wixsite.com/thesmollfestivoll"
  },
  {
    id: "9",
    datetime: "samedi 24 mai 2025 à 10h00",
    name: "Balade nature",
    location: {
      place: "Médiathèque",
      city: "CUGAND",
      department: "85",
    },
    price: "",
    audience: "tout public de 4 à 12 ans avec accompagnateur, 1h30, sur inscription",
  },
  {
    id: "13",
    datetime: "samedi 24 mai 2025 à 10h00",
    name: "Grandeur nature : activités en familles",
    location: {
      place: "L'Abel Guinguette",
      city: "MONNIERES",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "14",
    datetime: "samedi 24 mai 2025 de 10h00",
    endTime: "17h00",
    name: "Atelier soudure Good Steel",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "15",
    datetime: "samedi 24 mai 2025 de 10h00",
    endTime: "17h00",
    name: "Festi'liens : rencontre avec les associations qui font bouger le Pallet",
    location: {
      place: "Salle polyvalente",
      city: "LE PALLET",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "16",
    datetime: "samedi 24 mai 2025",
    name: "Concert baroque : (Vivaldi, Pergolese, Bach)",
    location: {
      place: "Église Saint-Martin-de-Vertou",
      city: "VERTOU",
      department: "44",
    },
    price: "gratuit",
    audience: "",
  },
  {
    id: "17",
    datetime: "samedi 24 mai 2025",
    name: "LES MASCARADES",
    location: {
      place: "",
      city: "CLISSON",
      department: "44",
    },
    price: "gratuit",
    audience: "",
  },
  {
    id: "18",
    datetime: "samedi 24 mai 2025",
    name: "Festival Lid ar morrigan VII : Skálmöld (ISL, Viking Folk Metal) / Nytt Land (RU Folk Chamanique) / Grimner (SUE, Folk / Pagan Metal) / Tanneurs de Drac (FR Folk / Rock médiéval) / Boisson Divine (FR Heavy Folk Metal) / Cuélebre (ES Pagan folk traditionnel) / Sorcières (FR Black / folk metal) / Aelad (FR Folk acoustique) / Flétan (FR Rock Pagan)",
    location: {
      place: "Le Champilambart",
      city: "VALLET",
      department: "44",
    },
    price: "30€",
    audience: "",
  },
  {
    id: "19",
    datetime: "samedi 24 mai 2025",
    name: "SMÖLL FESTIVÖLL #11 : Avalanche Kaito /Cyril Cyril",
    location: {
      place: "tba",
      city: "SAINT LUMINE DE CLISSON",
      department: "",
    },
    price: "14€",
    audience: "",
    url: "https://thesmollfestivoll.wixsite.com/thesmollfestivoll"
  },
  {
    id: "20",
    datetime: "dimanche 25 mai 2025 de 8h00",
    endTime: "18h00",
    name: "Bonne Fontaine fait son vide-grenier",
    location: {
      place: "Bonne Fonaine",
      city: "VALLET",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "21",
    datetime: "dimanche 25 mai 2025 de 8h00",
    endTime: "18h00",
    name: "Vide Grenier",
    location: {
      place: "Espace Sévria",
      city: "HAYE FOUASSIERE",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "22",
    datetime: "dimanche 25 mai 2025 de 9h00",
    endTime: "17h00",
    name: "Vide Grenier",
    location: {
      place: "Super U",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "23",
    datetime: "dimanche 25 mai 2025 de 9h00",
    endTime: "18h00",
    name: "33ème salon des collectionneurs",
    location: {
      place: "Pavillon des Nourrices, Place de l'Hôtel de Ville, Moulin de la Tour",
      city: "MONTAIGU",
      department: "85",
    },
    price: "",
    audience: "",
  },
  {
    id: "24",
    datetime: "dimanche 25 mai 2025 de 14h00",
    endTime: "17h00",
    name: "Atelier couture Fil Good thématique",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "25",
    datetime: "dimanche 25 mai 2025 de 16h00",
    endTime: "21h00",
    name: "Les dominique : Rudy Box theater / Lambe Lambe / Chile tiempo y teatros en miniature",
    location: {
      place: "I comme ICI",
      city: "SAINT LUMINE DE CLISSON",
      department: "44",
    },
    price: "PAF + adhésion prix libre",
    audience: "",
  },
  {
    id: "26",
    datetime: "dimanche 25 mai 2025",
    name: "LES MASCARADES",
    location: {
      place: "",
      city: "CLISSON",
      department: "44",
    },
    price: "gratuit",
    audience: "",
  },
  {
    id: "27",
    datetime: "mardi 27 mai 2025 à 18h30",
    name: "Conférence : « Moondog à travers le 20ème sicècle » par Amaury Cornut",
    location: {
      place: "Médiathèque",
      city: "CUGAND",
      department: "85",
    },
    price: "",
    audience: "tout public, 1h30, sur inscription de préférence",
  },
  {
    id: "28",
    datetime: "mardi 27 mai 2025 à 20h00",
    name: "Désembobinage présente « La cravate » d'Etienne Chaillou & Mathias Théry (projection/discussion)",
    location: {
      place: "Cercle Olivier de Clisson",
      city: "CLISSON",
      department: "44",
    },
    price: "prix libre",
    audience: "",
  },
  {
    id: "29",
    datetime: "mercredi 28 mai 2025 de 10h30",
    endTime: "12h00",
    name: "Club Connaître et Protéger la Nature (3-6 ans)",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "30",
    datetime: "mercredi 28 mai 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "31",
    datetime: "mercredi 28 mai 2025 à 15h00",
    name: "Le petit atelier : Book art",
    location: {
      place: "La Récupérette",
      city: "SAINT LUMINE DE CLISSON",
      department: "44",
    },
    price: "adhésion",
    audience: "",
  },
  {
    id: "32",
    datetime: "vendredi 30 mai 2025 à 18h00",
    name: "Nouvelle expo et vernissage de Gaëlle Jumelais",
    location: {
      place: "Librairie les villes invisibles",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "en très libre",
  },
  {
    id: "33",
    datetime: "vendredi 30 mai 2025 de 18h00",
    endTime: "03h00",
    name: "Vineyard Station Festival (dub-électro-reggae)",
    location: {
      place: "",
      city: "LA REMAUDIERE",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "34",
    datetime: "samedi 31 mai 2025",
    name: "Fête du jeu",
    location: {
      place: "Médiathèque Geneviève Couteau",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "35",
    datetime: "samedi 31 mai 2025",
    name: "Vineyard Station Festival (dub-électro-reggae)",
    location: {
      place: "",
      city: "LA REMAUDIERE",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "37",
    datetime: "dimanche 1er juin 2025",
    name: "Vide grenier",
    location: {
      place: "Rue des Ouches, Rue du Paradis, Bas Briacé",
      city: "LE LANDREAU",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "38",
    datetime: "dimanche 1er juin 2025 à 11h00",
    name: "DAMAline DUNE (lecture et poésie) : « les délices du patriarcat »",
    location: {
      place: "Au jardin du Paradis",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "10€",
    audience: "",
  },
  {
    id: "39",
    datetime: "dimanche 1er juin 2025 de 16h00",
    endTime: "21h00",
    name: "Les dominique : Grzzz (punk indus qui grince)",
    location: {
      place: "I comme ICI",
      city: "SAINT LUMINE DE CLISSON",
      department: "44",
    },
    price: "PAF + adhésion prix libre",
    audience: "",
  },
  {
    id: "40",
    datetime: "lundi 2 juin 2025 de 09h00",
    endTime: "17h00",
    name: "Lundi désossage (et grignotages !)",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "41",
    datetime: "mercredi 4 juin 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "42",
    datetime: "mercredi 4 juin 2025 à 16h30",
    name: "Rendez-vous conte",
    location: {
      place: "Bibliothèque des Changes",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "",
    audience: "à partir de 3 ans",
  },
  {
    id: "43",
    datetime: "mercredi 4 juin 2025 à 17h15",
    name: "Raconte-moi une histoire",
    location: {
      place: "Médiathèque Au fil des mots",
      city: "GORGES",
      department: "44",
    },
    price: "",
    audience: "à partir de 3 ans",
  },
  {
    id: "44",
    datetime: "jeudi 5 juin 2025 de 17h00",
    endTime: "20h00",
    name: "Atelier mécanique vélo pour femmes",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "45",
    datetime: "jeudi 5 juin 2025 de 18h00",
    endTime: "20h00",
    name: "Répétition ouverte au public de la chorale Vocal Vibes",
    location: {
      place: "Village Henri IV",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "46",
    datetime: "jeudi 5 juin 2025 à 20h00",
    name: "Conférence : Confier et accueillir un bébé allaité",
    location: {
      place: "Complexe de la Margerie",
      city: "GORGES",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "47",
    datetime: "vendredi 6 juin 2025",
    name: "Les Pestaculaires",
    location: {
      place: "",
      city: "MONTAIGU",
      department: "85",
    },
    price: "prix libre",
    audience: "",
  },
  {
    id: "48",
    datetime: "vendredi 6 juin 2025 dès 19h00",
    name: "Fête de la musique : DJ Bassline ft. Chilly Jay",
    location: {
      place: "Brut",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "entrée libre",
    audience: "",
  },
  {
    id: "49",
    datetime: "samedi 7 juin 2025",
    name: "Les Pestaculaires",
    location: {
      place: "",
      city: "MONTAIGU",
      department: "85",
    },
    price: "prix libre",
    audience: "",
  },
  {
    id: "50",
    datetime: "samedi 7 juin 2025 à partir de 15h00",
    name: "TOPO(S)#3- Label Parole : bibliothèque vivante / Un p'tit vélo dans la tête / mini-spectacle / Titre définitif* (*titre provisoire) / enquête sur lie / Parler de femmes « inconnues » / Le P.A.R.D.I / Le Bal à Boby / Haies vives",
    location: {
      place: "Divers lieux",
      city: "LA HAYE FOUASSIERE",
      department: "44",
    },
    price: "gratuit",
    audience: "",
  },
  {
    id: "51",
    datetime: "samedi 7 juin 2025 de 14h00",
    endTime: "17h00",
    name: "Atelier couture libre Fil Good",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "52",
    datetime: "samedi 7 juin 2025 de 10h00",
    endTime: "18h30",
    name: "MON PETIT FESTIVAL : 5ème édition",
    location: {
      place: "Espace Bellevue",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "gratuit-5€",
    audience: "",
  },
  {
    id: "53",
    datetime: "samedi 7 juin 2025 à 15h00",
    name: "Club ado",
    location: {
      place: "Médiathèque Geneviève Couteau",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "+13 ans",
  },
  {
    id: "54",
    datetime: "samedi 7 juin 2025 à partir de 17h00",
    name: "TBA",
    location: {
      place: "La Guinguette Cara'bella",
      city: "LE LANDREAU",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "55",
    datetime: "dimanche 8 juin 2025 de 8h00",
    endTime: "18h00",
    name: "Vide Grenier de l'Amicale Laïque de Mouzillon",
    location: {
      place: "Eugène Guérin, Route de la Prée, La Martinière",
      city: "MOUZILLON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "56",
    datetime: "dimanche 8 juin 2025 de 8h00",
    endTime: "18h00",
    name: "Vide Grenier",
    location: {
      place: "La Cantine d'Embreil",
      city: "SAINT JULIEN DE CONCELLES",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "57",
    datetime: "dimanche 8 juin 2025 de 16h00",
    endTime: "21h00",
    name: "Les dominique :Thomas Carabistouille / voyage de contes (tout public)",
    location: {
      place: "I comme ICI",
      city: "SAINT LUMINE DE CLISSON",
      department: "44",
    },
    price: "PAF + adhésion prix libre",
    audience: "",
  },
  {
    id: "58",
    datetime: "dimanche 8 juin 2025 à partir de 17h00",
    name: "TBA",
    location: {
      place: "La Guinguette Cara'bella",
      city: "LE LANDREAU",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "59",
    datetime: "mercredi 11 juin 2025 à 10h30",
    name: "Histoire pour petites oreilles",
    location: {
      place: "Médiathèque Au fil des mots",
      city: "GORGES",
      department: "44",
    },
    price: "",
    audience: "de 0 à 3 ans, sur inscription",
  },
  {
    id: "60",
    datetime: "mercredi 11 juin 2025 à 12h00",
    name: "Les interludes : Sieste musicale",
    location: {
      place: "Médiathèque Geneviève Couteau",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "61",
    datetime: "mercredi 11 juin 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "62",
    datetime: "jeudi 12 juin 2025 à 19h00",
    name: "Féminisme : « Être un allié », une soirée animée par Les Super Féministes : pour les hommes qui s'intéressent au féminisme mais qui ne savent pas par où commencer",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "prix libre",
    audience: "",
  },
  {
    id: "63",
    datetime: "vendredi 13 juin 2025 de 17h00",
    endTime: "23h00",
    name: "Portes ouvertes + AG + soirée festive",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "64",
    datetime: "vendredi 13 juin 2025 à 20h00",
    name: "Musique : Camille et Matthieu Saglio Cie Anaya",
    location: {
      place: "Médiathèque",
      city: "CLISSON",
      department: "44",
    },
    price: "gratuit",
    audience: "",
  },
  {
    id: "65",
    datetime: "vendredi 13 juin 2025 à 20h00",
    name: "Concert : Marteau / Pelegrin / Les hommes crabes",
    location: {
      place: "Les Papas Brasseurs",
      city: "CLISSON",
      department: "44",
    },
    price: "entrée libre",
    audience: "",
  },
  {
    id: "66",
    datetime: "samedi 14 juin 2025",
    name: "L'art dans les jardins",
    location: {
      place: "Fromaget & Gaumier",
      city: "CUGAND",
      department: "85",
    },
    price: "",
    audience: "",
  },
  {
    id: "67",
    datetime: "samedi 14 juin 2025 à 10h00",
    name: "Le tipi des petits",
    location: {
      place: "Médiathèque Geneviève Couteau",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "de 0 à 3 ans",
  },
  {
    id: "68",
    datetime: "samedi 14 juin 2025 à 10h30",
    name: "Café littéraire avec Anthony Gaté",
    location: {
      place: "Médiathèque",
      city: "CUGAND",
      department: "85",
    },
    price: "",
    audience: "tout public, 1h30, sur inscription de préférence",
  },
  {
    id: "69",
    datetime: "samedi 14 juin 2025 de 16h00",
    endTime: "00h00",
    name: "Fête de la musique",
    location: {
      place: "Centre Ville",
      city: "CLISSON",
      department: "44",
    },
    price: "gratuit",
    audience: "",
  },
  {
    id: "70",
    datetime: "samedi 14 juin 2025 à 23h00",
    name: "Concert : Koman Douman (reggae)",
    location: {
      place: "Café des cordeliers",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "71",
    datetime: "dimanche 15 juin 2025",
    name: "L'art dans les jardins",
    location: {
      place: "Fromaget & Gaumier",
      city: "CUGAND",
      department: "85",
    },
    price: "",
    audience: "",
  },
  {
    id: "72",
    datetime: "dimanche 15 juin 2025 de 16h00",
    endTime: "21h00",
    name: "Les dominique : Alexandre Chanoine / Neige percée / Le Crabe / Performance flamenco/noise/rap/xp",
    location: {
      place: "I comme ICI",
      city: "SAINT LUMINE DE CLISSON",
      department: "44",
    },
    price: "PAF + adhésion prix libre",
    audience: "",
  },
  {
    id: "73",
    datetime: "dimanche 15 juin 2025 à 16h30",
    name: "Concert de musique actuelle",
    location: {
      place: "Salle Sévria",
      city: "LA HAYE-FOUASSIERE",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "74",
    datetime: "mardi 17 juin 2025 à 20h00",
    name: "Brin de Sol'Haye / OH-N149",
    location: {
      place: "Château de Rochefort",
      city: "LA HAYE-FOUASSIERE",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "75",
    datetime: "mercredi 18 juin 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "76",
    datetime: "mercredi 18 juin 2025 à 16h30",
    name: "Le coffre à histoires",
    location: {
      place: "Médiathèque Geneviève Couteau",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "à partir de 3 ans",
  },
  {
    id: "77",
    datetime: "mercredi 18 juin 2025 à 20h00",
    name: "Concert : Soul Trap (blues/reggea)",
    location: {
      place: "Le Quebreizh",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "78",
    datetime: "vendredi 20 juin 2025 à 18h00",
    name: "Fête de la musique",
    location: {
      place: "Le Port",
      city: "LA HAYE-FOUASSIERE",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "79",
    datetime: "vendredi 20 juin 2025",
    name: "BRELFEST :...",
    location: {
      place: "verger du Petit Coubrenier",
      city: "CUGAND",
      department: "85",
    },
    price: "prix libre",
    audience: "",
  },
  {
    id: "80",
    datetime: "samedi 21 juin 2025 de 18h00",
    endTime: "22h00",
    name: "Soirée impro danse & musique avec Meritxell Checa Esteban et le groupe de musique La Berlue",
    location: {
      place: "Henri IV",
      city: "CLISSON",
      department: "44",
    },
    price: "5€ (pas de CB)",
    audience: "",
  },
  {
    id: "81",
    datetime: "samedi 21 juin 2025",
    name: "BRELFEST :...",
    location: {
      place: "verger du Petit Coubrenier",
      city: "CUGAND",
      department: "85",
    },
    price: "prix libre",
    audience: "",
  },
  {
    id: "82",
    datetime: "dimanche 22 juin 2025",
    name: "BRELFEST :...",
    location: {
      place: "verger du Petit Coubrenier",
      city: "CUGAND",
      department: "85",
    },
    price: "prix libre",
    audience: "",
  },
  {
    id: "83",
    datetime: "dimanche 22 juin 2025 de 14h00",
    endTime: "17h00",
    name: "Atelier couture Fil Good thématique",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "84",
    datetime: "mercredi 25 juin 2025 de 10h30",
    endTime: "12h00",
    name: "Club Connaître et Protéger la Nature (3-6 ans)",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "85",
    datetime: "mercredi 25 juin 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "86",
    datetime: "mercredi 25 juin 2025 à 16h30",
    name: "Club lecture jeunesse",
    location: {
      place: "Médiathèque Geneviève Couteau",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "9-12 ans",
  },
  {
    id: "87",
    datetime: "vendredi 27 juin 2025 à 19h00",
    name: "Blabla Night",
    location: {
      place: "Médiathèque Geneviève Couteau",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "88",
    datetime: "vendredi 27 juin 2025 à 19h00",
    name: "Apéro concert dans le parc : lecture musicale / Miam's : la chanson au menu",
    location: {
      place: "Médiathèque",
      city: "CUGAND",
      department: "85",
    },
    price: "tout public",
    audience: "",
  },
  {
    id: "89",
    datetime: "vendredi 27 juin 2025 à 19h30",
    name: "Soirée moules frites",
    location: {
      place: "Brut",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "",
    audience: "sur réservation",
  },
  {
    id: "90",
    datetime: "samedi 28 juin 2025",
    name: "Slam as you are souffle sa 2ème bougie : festival de Slam poésie",
    location: {
      place: "lieu TBA",
      city: "",
      department: "",
    },
    price: "",
    audience: "",
  },
  {
    id: "91",
    datetime: "samedi 28 juin 2025 à partir de 19h30",
    name: "Soirée Jeux de société avec Quentin de Chez L'Hippogriffe",
    location: {
      place: "Brut",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "",
    audience: "sur réservation",
  },
  {
    id: "92",
    datetime: "mardi 1er juillet 2025 à 20h00",
    name: "Concert : PA (swing musette)",
    location: {
      place: "Complexe de la Margerie",
      city: "GORGES",
      department: "44",
    },
    price: "entrée libre",
    audience: "",
  },
  {
    id: "93",
    datetime: "mercredi 2 juillet 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "94",
    datetime: "mercredi 2 juillet 2025 à 15h00",
    name: "Atelier dessin avec Frédérique Brémaud : Pas besoin de très bien dessiner pour faire de la BD !",
    location: {
      place: "Médiathèque Geneviève Couteau",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "à partir de 7 ans, sur inscription",
  },
  {
    id: "95",
    datetime: "mercredi 2 juillet 2025 à 17h15",
    name: "Raconte-moi une histoire",
    location: {
      place: "Médiathèque Au fil des mots",
      city: "GORGES",
      department: "44",
    },
    price: "",
    audience: "à partir de 3 ans",
    emoji: "📖",
  },
  {
    id: "96",
    datetime: "vendredi 4 juillet 2025 à 20h00",
    name: "5ème anniversaire : NY-KO (garage funk) / I am Fez (DJ set)",
    location: {
      place: "Les Papas Brasseurs",
      city: "CLISSON",
      department: "44",
    },
    price: "entrée libre",
    audience: "",
  },
  {
    id: "97",
    datetime: "samedi 5 juillet 2025 à 10h30",
    name: "Bouqu'café",
    location: {
      place: "Bibliothèque des Changes",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "",
    audience: "",
    emoji: "📖",
  },
  {
    id: "98",
    datetime: "samedi 5 juillet 2025 à 11h00",
    name: "Rencontre littéraire avec Diana Vivarelli",
    location: {
      place: "Médiathèque Geneviève Couteau",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "public adulte, sur inscription",
  },
  {
    id: "99",
    datetime: "samedi 5 juillet 2025 à partir de 18h00",
    name: "Fête de l'été",
    location: {
      place: "Le Moulin des Landes",
      city: "LA HAYE-FOUASSIERE",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "100",
    datetime: "samedi 5 juillet 2025 à 19h00",
    name: "Les feux de Gétigné",
    location: {
      place: "Complexe Sportif",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "101",
    datetime: "samedi 5 juillet 2025",
    name: "Festival Les Italiennes",
    location: {
      place: "NC",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "102",
    datetime: "dimanche 6 juillet 2025 à 11h00",
    name: "DAMAline DUNE (lecture et poésie) avec Aurèle Salmon",
    location: {
      place: "Au jardin du Paradis",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "10€",
    audience: "",
  },
  {
    id: "103",
    datetime: "dimanche 6 juillet 2025",
    name: "Festival Les Italiennes",
    location: {
      place: "NC",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "104",
    datetime: "du mardi 8 au mercredi 9 juillet 2025",
    name: "Nuitées : balade contée, grands jeux, chasse aux trésors (2 animatreurs, repas)",
    location: {
      place: "Non communiqué",
      city: "",
      department: "44",
    },
    price: "",
    audience: "réservé aux enfants de 2018-19-20, 10 enfants maximum",
  },
  {
    id: "105",
    datetime: "mercredi 9 juillet 2025 à 10h30",
    name: "Histoire pour petites oreilles",
    location: {
      place: "Médiathèque Au fil des mots",
      city: "GORGES",
      department: "44",
    },
    price: "",
    audience: "de 0 à 3 ans, sur inscription",
  },
  {
    id: "106",
    datetime: "mercredi 9 juillet 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "107",
    datetime: "mercredi 9 juillet 2025 à 17h00",
    name: "Musique et humour dans les arbres : La chorale perchée, Théâtre des Sept Lieues",
    location: {
      place: "Petit Bois du complexe de la Margerie",
      city: "GORGES",
      department: "44",
    },
    price: "gratuit",
    audience: "",
  },
  {
    id: "108",
    datetime: "jeudi 10 juillet 2025 à 10h30",
    name: "Spectacle : « Les rencontres de la plume »",
    location: {
      place: "Médiathèque",
      city: "CUGAND",
      department: "85",
    },
    price: "",
    audience: "6 mois à 6 ans, 35min, sur inscription",
  },
  {
    id: "109",
    datetime: "jeudi 10 juillet 2025 à 10h30",
    name: "Histoires vagabondes animées par la bibliothèque des changes",
    location: {
      place: "Parc du Vallon",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "110",
    datetime: "dimanche 13 juillet 2025 à partir de 19h00",
    name: "Feu d'artifice et bal des pompiers",
    location: {
      place: "Place de la Trinité - Garenne Valentin",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "111",
    datetime: "du mardi 15 au vendredi 18 juillet 2025",
    name: "3, 2, 1, partez ! (sarbacane, nuit en tente, tir à l'arc, course d'orientation, piscine, veillée)",
    location: {
      place: "Non communiqué",
      city: "",
      department: "44",
    },
    price: "",
    audience: "GS, CP, CE1, 24 places, inscription le 14 mai",
  },
  {
    id: "112",
    datetime: "mercredi 16 juillet 2025 de 10h00",
    endTime: "12h00",
    name: "Rencontre avec l'illustrateur Tonitorfer",
    location: {
      place: "Médiathèque",
      city: "CUGAND",
      department: "85",
    },
    price: "",
    audience: "4 ans et +, 2h, sur inscription",
  },
  {
    id: "113",
    datetime: "mercredi 16 juillet 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "114",
    datetime: "samedi 19 juillet 2025 à 10h30",
    name: "Fabrication d'arbre en papier recyclé",
    location: {
      place: "Médiathèque Au fil des mots",
      city: "GORGES",
      department: "44",
    },
    price: "",
    audience: "à partir de 5 ans, sur inscription",
  },
  {
    id: "115",
    datetime: "du lundi 21 au vendredi 25 juillet 2025",
    name: "Challenge en plein air (canoë-kayak, carabine laser, nuit en tente, tir à l'arc, paddle, piscine, veillées)",
    location: {
      place: "Non communiqué",
      city: "",
      department: "44",
    },
    price: "",
    audience: "CE2,CM1, CM2, 24 places, inscription le 14 mai",
  },
  {
    id: "116",
    datetime: "du mardi 22 au mercredi 23 juillet 2025",
    name: "Nuitées : balade contée, grands jeux, chasse aux trésors (2 animatreurs, repas)",
    location: {
      place: "Non communiqué",
      city: "",
      department: "44",
    },
    price: "",
    audience: "réservé aux enfants de 2018-19-20, 10 enfants maximum",
  },
  {
    id: "117",
    datetime: "mercredi 23 juillet 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "118",
    datetime: "vendredi 25 juillet 2025 à partir de 19h00",
    name: "Les nocturnes de Clisson",
    location: {
      place: "Centre Ville",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "119",
    datetime: "mercredi 30 juillet 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "120",
    datetime: "mercredi 6 août 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "121",
    datetime: "mercredi 13 août 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "122",
    datetime: "mercredi 13 août 2025",
    name: "Concert : Mélisande (électrotrad)",
    location: {
      place: "Le Quebreizh",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "123",
    datetime: "mercredi 20 août 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "124",
    datetime: "vendredi 22 août 2025",
    name: "Clisson Vintage # 5",
    location: {
      place: "",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "125",
    datetime: "vendredi 22 août 2025 à partir de 19h00",
    name: "Les nocturnes de Clisson",
    location: {
      place: "Centre Ville",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "126",
    datetime: "samedi 23 août 2025",
    name: "Clisson Vintage # 5",
    location: {
      place: "",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "127",
    datetime: "dimanche 24 août 2025",
    name: "Clisson Vintage # 5",
    location: {
      place: "",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "128",
    datetime: "mercredi 27 août 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "129",
    datetime: "jeudi 28 août 2025 à 10h30",
    name: "Histoires vagabondes animées par la bibliothèque des changes",
    location: {
      place: "Parc du Vallon",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "130",
    datetime: "vendredi 29 août 2025 à 19h30",
    name: "Les Petites Scènes",
    location: {
      place: "Parc du Vallon",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "131",
    datetime: "samedi 30 août 2025 à partir de 17h00",
    name: "Gorges en fête",
    location: {
      place: "Rue de la Sèvre",
      city: "GORGES",
      department: "44",
    },
    price: "entrée libre",
    audience: "",
  },
  {
    id: "132",
    datetime: "mercredi 3 septembre 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "133",
    datetime: "mercredi 10 septembre 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "134",
    datetime: "mercredi 17 septembre 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "135",
    datetime: "dimanche 21 septembre 2025",
    name: "Vide grenier automnal",
    location: {
      place: "Place de la Bosselle et Rue de la Bosselle",
      city: "REMOUILLÉ",
      department: "44",
    },
    price: "",
    audience: "",
    emoji: "📦",
  },
  {
    id: "136",
    datetime: "lundi 29 septembre 2025 à 20h00",
    name: "LES CLISSONNANTES : Projection du film « Farinelli » de Gérard Corbiau",
    location: {
      place: "Cinéma Le Connétable",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "réserver",
  },
  {
    id: "137",
    datetime: "mercredi 1er octobre 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "138",
    datetime: "jeudi 2 octobre 2025 à 20h30",
    name: "LES CLISSONNANTES : Concert d'inauguration",
    location: {
      place: "Espace Saint Jacques",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "réserver",
  },
  {
    id: "139",
    datetime: "vendredi 3 octobre 2025 à 20h30",
    name: "LES CLISSONNANTES : Grand concert d'ouverture",
    location: {
      place: "Espace Arlekino",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "réserver",
  },
  {
    id: "140",
    datetime: "samedi 4 octobre 2025 à 11h00",
    name: "LES CLISSONNANTES : « Bach et l'Italie »",
    location: {
      place: "Espace Saint Jacques",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "réserver",
  },
  {
    id: "141",
    datetime: "samedi 4 octobre 2025 à 12h15",
    name: "LES CLISSONNANTES : conférence « Musique au Moyen Âge » par Nicolas Jounis",
    location: {
      place: "Espace Saint Jacques",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "réserver",
  },
  {
    id: "142",
    datetime: "samedi 4 octobre 2025 à 14h00",
    name: "LES CLISSONNANTES : « Folle Journée en Italie »",
    location: {
      place: "Espace Arlekino",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "réserver",
  },
  {
    id: "143",
    datetime: "samedi 4 octobre 2025 à 16h00",
    name: "LES CLISSONNANTES : « En passant par Florence… »",
    location: {
      place: "Espace Saint Jacques",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "réserver",
  },
  {
    id: "144",
    datetime: "samedi 4 octobre 2025 à 18h00",
    name: "LES CLISSONNANTES : « Notte d'Opera alla Scala »",
    location: {
      place: "Espace Arlekino",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "réserver",
  },
  {
    id: "145",
    datetime: "samedi 4 octobre 2025 à 20h30",
    name: "LES CLISSONNANTES : « Le Trésor de la Chapelle Sixtine »",
    location: {
      place: "Église Notre-Dame",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "réserver",
  },
  {
    id: "146",
    datetime: "dimanche 5 octobre 2025 à 10h45",
    name: "LES CLISSONNANTES : « Escales à Vienne et Paris… »",
    location: {
      place: "Espace Saint Jacques",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "réserver",
  },
  {
    id: "147",
    datetime: "dimanche 5 octobre 2025 à 12h15",
    name: "LES CLISSONNANTES : Marine Allain (Pop – Soul – Jazz)",
    location: {
      place: "Sous les Halles",
      city: "CLISSON",
      department: "44",
    },
    price: "gratuit",
    audience: "",
  },
  {
    id: "148",
    datetime: "dimanche 5 octobre 2025 à 14h00",
    name: "LES CLISSONNANTES : « Voyage en Italie »",
    location: {
      place: "Espace Arlekino",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "réserver",
  },
  {
    id: "149",
    datetime: "dimanche 5 octobre 2025 à 16h00",
    name: "LES CLISSONNANTES : « Harmonies sacrées d'Italie »",
    location: {
      place: "Église Notre-Dame",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "réserver",
  },
  {
    id: "150",
    datetime: "dimanche 5 octobre 2025 à 18h00",
    name: "LES CLISSONNANTES : « Le Concert des Légendes »",
    location: {
      place: "Espace Arlekino",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "réserver",
  },
  {
    id: "151",
    datetime: "mercredi 8 octobre 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "152",
    datetime: "mercredi 15 octobre 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "153",
    datetime: "mercredi 22 octobre 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "154",
    datetime: "mercredi 29 octobre 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "155",
    datetime: "vendredi 31 octobre 2025",
    name: "WESTILL FEST IX :...",
    location: {
      place: "tba",
      city: "",
      department: "",
    },
    price: "",
    audience: "",
  },
  {
    id: "156",
    datetime: "samedi 1er novembre 2025",
    name: "WESTILL FEST IX :...",
    location: {
      place: "tba",
      city: "",
      department: "",
    },
    price: "",
    audience: "",
  },
  {
    id: "157",
    datetime: "mercredi 5 novembre 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "158",
    datetime: "mercredi 12 novembre 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "159",
    datetime: "mercredi 19 novembre 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "160",
    datetime: "mercredi 26 novembre 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "161",
    datetime: "mercredi 3 décembre 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "162",
    datetime: "mercredi 10 décembre 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "163",
    datetime: "samedi 13 décembre 2025 à 18h00",
    name: "ONPL : « La Petite Sirène » direction Chloé Meyzie",
    location: {
      place: "Le Champilambart",
      city: "VALLET",
      department: "44",
    },
    price: "",
    audience: "à partir de 4 ans",
  },
  {
    id: "164",
    datetime: "mercredi 17 décembre 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "165",
    datetime: "mercredi 7 janvier 2026 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "166",
    datetime: "samedi 11 janvier 2026 de 14h00",
    endTime: "19h00",
    name: "Broc' land geek",
    location: {
      place: "Espace Arlekino",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "167",
    datetime: "dimanche 12 janvier 2026 de 9h00",
    endTime: "17h00",
    name: "Broc' land geek",
    location: {
      place: "Espace Arlekino",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "168",
    datetime: "mercredi 14 janvier 2026 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "169",
    datetime: "mercredi 21 janvier 2026 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  // Événements passés
  {
    id: "10",
    datetime: "lundi 19 mai 2025 à 15h00",
    name: "Exposition photo",
    location: {
      place: "Médiathèque",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "11",
    datetime: "mardi 20 mai 2025 à 14h00",
    name: "Atelier d'écriture",
    location: {
      place: "Centre culturel",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "12",
    datetime: "mardi 20 mai 2025 de 21h00",
    endTime: "23h00",
    name: "Dev. ephemeride 2.0",
    location: {
      place: "Chez Amaury",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "36",
    datetime: "jeudi 22 mai 2025 à 20h00",
    name: "Club Ciné : « Grease »",
    location: {
      place: "Cinéma Le connétable (salle 1)",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  }
];
