import { Event } from "./types";

export const sampleEvents: Event[] = [
  {
    id: "1",
    datetime: "mercredi 21 mai 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "2",
    datetime: "mercredi 21 mai 2025 à 16h30",
    name: "Le coffre à histoires",
    location: {
      place: "Médiathèque Geneviève Couteau",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "à partir de 3 ans",
  },
  {
    id: "3",
    datetime: "mercredi 21 mai 2025 à 16h30",
    name: "Échange ta lecture",
    location: {
      place: "Bibliothèque des changes",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "",
    audience: "8-12 ans",
  },
  {
    id: "4",
    datetime: "vendredi 23 mai 2025 à 19h00",
    name: "Rencontre avec Fabien Lebrun",
    location: {
      place: "Librairie les villes invisibles",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "en très libre",
  },
  {
    id: "5",
    datetime: "vendredi 23 mai 2025 à 19h00",
    name: "La Fête des voisins : pique nique zéro déchets & concours de pétanque (en partenariat avec Granit)",
    location: {
      place: "Porte de Palzaire",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "6",
    datetime: "vendredi 23 mai 2025 à 19h30",
    name: "Les Petites Scènes",
    location: {
      place: "Parc du Vallon",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "7",
    datetime: "vendredi 23 mai 2025 à 20h30",
    name: "Danse et musique : « [F] »",
    location: {
      place: "Auditorium du complexe de la Margerie",
      city: "GORGES",
      department: "44",
    },
    price: "5-8€",
    audience: "tout public à partir de 10 ans",
  },
  {
    id: "8",
    datetime: "vendredi 23 mai 2025 à 18h00",
    name: "SMÖLL FESTIVÖLL #11 : Slüg /RCD Soundsystem",
    location: {
      place: "Espace des Garennes",
      city: "SAINT LUMINE DE CLISSON",
      department: "44",
    },
    price: "prix libre",
    audience: "",
    url: "https://thesmollfestivoll.wixsite.com/thesmollfestivoll"
  },
  {
    id: "9",
    datetime: "samedi 24 mai 2025 à 10h00",
    name: "Balade nature",
    location: {
      place: "Médiathèque",
      city: "CUGAND",
      department: "85",
    },
    price: "",
    audience: "tout public de 4 à 12 ans avec accompagnateur, 1h30, sur inscription",
  },
  // Ajout des nouveaux événements
  {
    id: "13",
    datetime: "samedi 24 mai 2025 à 10h00",
    name: "Grandeur nature : activités en familles",
    location: {
      place: "L'Abel Guinguette",
      city: "MONNIERES",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "14",
    datetime: "samedi 24 mai 2025 de 10h00",
    endTime: "17h00",
    name: "Atelier soudure Good Steel",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "15",
    datetime: "samedi 24 mai 2025 de 10h00",
    endTime: "17h00",
    name: "Festi'liens : rencontre avec les associations qui font bouger le Pallet",
    location: {
      place: "Salle polyvalente",
      city: "LE PALLET",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "16",
    datetime: "samedi 24 mai 2025",
    name: "Concert baroque : (Vivaldi, Pergolese, Bach)",
    location: {
      place: "Église Saint-Martin-de-Vertou",
      city: "VERTOU",
      department: "44",
    },
    price: "gratuit",
    audience: "",
  },
  {
    id: "17",
    datetime: "samedi 24 mai 2025",
    name: "LES MASCARADES",
    location: {
      place: "",
      city: "CLISSON",
      department: "44",
    },
    price: "gratuit",
    audience: "",
  },
  {
    id: "18",
    datetime: "samedi 24 mai 2025",
    name: "Festival Lid ar morrigan VII : Skálmöld (ISL, Viking Folk Metal) / Nytt Land (RU Folk Chamanique) / Grimner (SUE, Folk / Pagan Metal) / Tanneurs de Drac (FR Folk / Rock médiéval) / Boisson Divine (FR Heavy Folk Metal) / Cuélebre (ES Pagan folk traditionnel) / Sorcières (FR Black / folk metal) / Aelad (FR Folk acoustique) / Flétan (FR Rock Pagan)",
    location: {
      place: "Le Champilambart",
      city: "VALLET",
      department: "44",
    },
    price: "30€",
    audience: "",
  },
  {
    id: "19",
    datetime: "samedi 24 mai 2025",
    name: "SMÖLL FESTIVÖLL #11 : Avalanche Kaito /Cyril Cyril",
    location: {
      place: "tba",
      city: "SAINT LUMINE DE CLISSON",
      department: "",
    },
    price: "14€",
    audience: "",
    url: "https://thesmollfestivoll.wixsite.com/thesmollfestivoll"
  },
  {
    id: "20",
    datetime: "dimanche 25 mai 2025 de 8h00",
    endTime: "18h00",
    name: "Bonne Fontaine fait son vide-grenier",
    location: {
      place: "Bonne Fonaine",
      city: "VALLET",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "21",
    datetime: "dimanche 25 mai 2025 de 8h00",
    endTime: "18h00",
    name: "Vide Grenier",
    location: {
      place: "Espace Sévria",
      city: "HAYE FOUASSIERE",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "22",
    datetime: "dimanche 25 mai 2025 de 9h00",
    endTime: "17h00",
    name: "Vide Grenier",
    location: {
      place: "Super U",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "23",
    datetime: "dimanche 25 mai 2025 de 9h00",
    endTime: "18h00",
    name: "33ème salon des collectionneurs",
    location: {
      place: "Pavillon des Nourrices, Place de l'Hôtel de Ville, Moulin de la Tour",
      city: "MONTAIGU",
      department: "85",
    },
    price: "",
    audience: "",
  },
  {
    id: "24",
    datetime: "dimanche 25 mai 2025 de 14h00",
    endTime: "17h00",
    name: "Atelier couture Fil Good thématique",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "25",
    datetime: "dimanche 25 mai 2025 de 16h00",
    endTime: "21h00",
    name: "Les dominique : Rudy Box theater / Lambe Lambe / Chile tiempo y teatros en miniatura",
    location: {
      place: "I comme ICI",
      city: "SAINT LUMINE DE CLISSON",
      department: "44",
    },
    price: "PAF + adhésion prix libre",
    audience: "",
  },
  {
    id: "26",
    datetime: "dimanche 25 mai 2025",
    name: "LES MASCARADES",
    location: {
      place: "",
      city: "CLISSON",
      department: "44",
    },
    price: "gratuit",
    audience: "",
  },
  {
    id: "27",
    datetime: "mardi 27 mai 2025 à 18h30",
    name: "Conférence : « Moondog à travers le 20ème sicècle » par Amaury Cornut",
    location: {
      place: "Médiathèque",
      city: "CUGAND",
      department: "85",
    },
    price: "",
    audience: "tout public, 1h30, sur inscription de préférence",
  },
  {
    id: "28",
    datetime: "mardi 27 mai 2025 à 20h00",
    name: "Désembobinage présente « La cravate » d'Etienne Chaillou & Mathias Théry (projection/discussion)",
    location: {
      place: "Cercle Olivier de Clisson",
      city: "CLISSON",
      department: "44",
    },
    price: "prix libre",
    audience: "",
  },
  {
    id: "29",
    datetime: "mercredi 28 mai 2025 de 10h30",
    endTime: "12h00",
    name: "Club Connaître et Protéger la Nature (3-6 ans)",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "30",
    datetime: "mercredi 28 mai 2025 de 14h00",
    endTime: "19h00",
    name: "Atelier vélo Good'Huile + vente de vélos d'occasion",
    location: {
      place: "La Solid'",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "31",
    datetime: "mercredi 28 mai 2025 à 15h00",
    name: "Le petit atelier : Book art",
    location: {
      place: "La Récupérette",
      city: "SAINT LUMINE DE CLISSON",
      department: "44",
    },
    price: "adhésion",
    audience: "",
  },
  {
    id: "32",
    datetime: "vendredi 30 mai 2025 à 18h00",
    name: "Nouvelle expo et vernissage de Gaëlle Jumelais",
    location: {
      place: "Librairie les villes invisibles",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "en très libre",
  },
  {
    id: "33",
    datetime: "vendredi 30 mai 2025 de 18h00",
    endTime: "03h00",
    name: "Vineyard Station Festival (dub-électro-reggae)",
    location: {
      place: "",
      city: "LA REMAUDIERE",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "34",
    datetime: "samedi 31 mai 2025",
    name: "Fête du jeu",
    location: {
      place: "Médiathèque Geneviève Couteau",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "35",
    datetime: "samedi 31 mai 2025",
    name: "Vineyard Station Festival (dub-électro-reggae)",
    location: {
      place: "",
      city: "LA REMAUDIERE",
      department: "44",
    },
    price: "",
    audience: "",
  },
  // Événements passés
  {
    id: "10",
    datetime: "lundi 19 mai 2025 à 15h00",
    name: "Exposition photo",
    location: {
      place: "Médiathèque",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "11",
    datetime: "mardi 20 mai 2025 à 14h00",
    name: "Atelier d'écriture",
    location: {
      place: "Centre culturel",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "12",
    datetime: "mardi 20 mai 2025 de 21h00",
    endTime: "23h00",
    name: "Dev. ephemeride 2.0",
    location: {
      place: "Chez Amaury",
      city: "GÉTIGNÉ",
      department: "44",
    },
    price: "",
    audience: "",
  },
  {
    id: "36",
    datetime: "jeudi 22 mai 2025 à 20h00",
    name: "Club Ciné : « Grease »",
    location: {
      place: "Cinéma Le connétable (salle 1)",
      city: "CLISSON",
      department: "44",
    },
    price: "",
    audience: "",
  }
];
