// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgjvfuzdnbvgxkbndwfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnanZmdXpkbmJ2Z3hrYm5kd2ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTAyMjUsImV4cCI6MjA2NDAyNjIyNX0.hm3SmiQ4BCV-hCBZr53Z9QNgqSpWylFtypNzDDWgelU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);